name: axstudio

networks:
  axstudio_net:
    name: axstudio_net

volumes:
  lf_pg_data:
  lfs_pg_data:
  clickhouse_data:
  minio_data:

services:
  # ---------------------------
  # Langflow + Postgres (Langflow는 소스 빌드)
  # ---------------------------
  lf-postgres:
    image: postgres:15-alpine
    container_name: lf-postgres
    environment:
      POSTGRES_USER: ${LF_PG_USER}
      POSTGRES_PASSWORD: ${LF_PG_PASSWORD}
      POSTGRES_DB: ${LF_PG_DB}
    volumes:
      - lf_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - axstudio_net

  langflow:
    build:
      context: ../langflow
      dockerfile: ${LANGFLOW_DOCKERFILE_PATH:-Dockerfile}
      args:
        BUILD_FRONTEND: "true"
    image: ax/langflow:local
    container_name: langflow
    depends_on:
      lf-postgres:
        condition: service_healthy
    ports:
      - "${LANGFLOW_PORT:-7860}:7860"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ✅ 런타임에 에디터블 설치 + watchfiles로 자동 재시작
    #command: >
    #  sh -lc "
    #  python -m pip install -q 'uvicorn[standard]' fastapi watchfiles &&
    #  python -m pip install -e /app &&
    #  python -m pip install -e /app/src/backend/base &&
    #  watchfiles --filter python
    #    'python -m langflow.langflow_launcher run --host 0.0.0.0 --port 7860'
    #    /app/src/backend
    #  "
    # ✅ 로컬 소스를 컨테이너에 제대로 마운트(루트 + backend 둘 다)
    #volumes:
    #  - ../langflow:/app:rw
    #  - ../langflow/src/backend:/app/src/backend:rw
    environment:
      LANGFLOW_DATABASE_URL: postgresql+psycopg://${LF_PG_USER}:${LF_PG_PASSWORD}@lf-postgres:5432/${LF_PG_DB}
      LANGFLOW_AUTO_LOGIN: ${LANGFLOW_AUTO_LOGIN:-false}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY:-}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY:-}
      LANGFUSE_HOST: ${LANGFUSE_HOST:-http://langfuse-web:3000}
      COE_BACKEND_URL: ${COE_BACKEND_URL:-http://host.docker.internal:8000}
      COE_RAG_URL: ${COE_RAG_URL:-http://localhost:8001}
      LANGFLOW_EXPOSED_ENV_VARS: "COE_BACKEND_URL,COE_RAG_URL"
      # ✅ 파이썬이 로컬 소스 먼저 보도록
      #PYTHONPATH: /app:/app/src/backend:/app/src/backend/base
      # 🔽 Phoenix 연동 핵심
      PHOENIX_API_KEY: ${PHOENIX_API_KEY}             # Phoenix(Arize) 대시보드에서 발급
      # 선택: OTel 표준 설정(명시적)
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL:-grpc}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://phoenix:4317}
      OTEL_EXPORTER_OTLP_HEADERS: "x-api-key=${PHOENIX_API_KEY}" #"Authorization=Bearer ${PHOENIX_API_KEY}"
      OTEL_EXPORTER_OTLP_TRACES_HEADERS: "x-api-key=${PHOENIX_API_KEY}" #"Authorization=Bearer ${PHOENIX_API_KEY}"
      OTEL_RESOURCE_ATTRIBUTES: service.name=langflow,service.namespace=axstudio
    restart: unless-stopped
    networks:
      - axstudio_net

  # ---------------------------
  # Langfuse 스택 (Langfuse는 소스 빌드)
  # ---------------------------
  lfs-postgres:
    image: postgres:15-alpine
    container_name: lfs-postgres
    environment:
      POSTGRES_USER: ${LFS_PG_USER}
      POSTGRES_PASSWORD: ${LFS_PG_PASSWORD}
      POSTGRES_DB: ${LFS_PG_DB}
    volumes:
      - lfs_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - axstudio_net

  redis:
    image: redis:7-alpine
    container_name: langfuse-redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - axstudio_net

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "9990:9990"
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1   # ← 권장(사용자/권한 관리 활성화)
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
     # - ./deployments/clickhouse/conf.d/:/etc/clickhouse-server/config.d:ro
      - ./clickhouse/conf.d/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml:ro
      - ./clickhouse/conf.d/remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml:ro
      - ./clickhouse/conf.d/macros.xml:/etc/clickhouse-server/config.d/macros.xml:ro
    command: >
      bash -c "sed -i 's|<tcp_port>9000</tcp_port>|<tcp_port>9990</tcp_port>|' /etc/clickhouse-server/config.xml
      && /entrypoint.sh"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8123/ping | grep -q 'Ok.'"]
      interval: 5s
      timeout: 2s
      retries: 30
    depends_on:
      zookeeper:
        condition: service_started
    networks:
      - axstudio_net

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9090" --address ":9091"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      # (옵션) 기본 버킷명도 compose에 명시해두면 다른 서비스와 한 눈에 맞출 수 있어요
      MINIO_MEDIA_BUCKET: ${MINIO_MEDIA_BUCKET:-langfuse-media}
      MINIO_EVENT_BUCKET: ${MINIO_EVENT_BUCKET:-langfuse-events}
    ports:
      - "9090:9090"   # 콘솔(UI)
      - "9091:9091"   # S3 API
    volumes:
      - minio_data:/data
    networks:
      - axstudio_net
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9091/minio/health/ready"]
      interval: 2s
      timeout: 5s
      retries: 60

  # --- 버킷 자동 생성용 원샷 init 잡 ---
  minio-init:
    image: alpine:3.20
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: ["/bin/sh", "-lc"]
    command: >
      set -eu;
      apk add --no-cache python3 py3-pip curl jq netcat-openbsd >/dev/null;
      pip install --no-cache-dir awscli >/dev/null;
      S3_EP=http://minio:9091;
      echo "Waiting for MinIO S3 API at $$S3_EP ...";
      i=0; while ! nc -z minio 9091 2>/dev/null; do i=$$((i+1)); [ $$i -gt 60 ] && echo "MinIO not ready" && exit 1; sleep 1; done;
      aws --endpoint-url "$$S3_EP" s3api create-bucket --bucket "$$MINIO_MEDIA_BUCKET" || true;
      aws --endpoint-url "$$S3_EP" s3api create-bucket --bucket "$$MINIO_EVENT_BUCKET" || true;
      echo "MinIO buckets ready."
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_MEDIA_BUCKET: ${MINIO_MEDIA_BUCKET:-langfuse-media}
      MINIO_EVENT_BUCKET: ${MINIO_EVENT_BUCKET:-langfuse-events}
    networks:
      - axstudio_net
    restart: "no"

  langfuse-web:
    build:
      context: ../langfuse               # ← 클론한 소스 루트(모노레포)
      dockerfile: ${LANGFUSE_WEB_DOCKERFILE_PATH:-web/Dockerfile}
    image: ax/langfuse-web:local
    container_name: langfuse-web
    depends_on:
      lfs-postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    ports:
      - "${LANGFUSE_PORT:-3000}:3000"
    environment:
      DATABASE_URL: postgresql://${LFS_PG_USER}:${LFS_PG_PASSWORD}@lfs-postgres:5432/${LFS_PG_DB}
      DIRECT_URL: postgresql://${LFS_PG_USER}:${LFS_PG_PASSWORD}@lfs-postgres:5432/${LFS_PG_DB}
      CLICKHOUSE_MIGRATION_URL: clickhouse://clickhouse:9990
      CLICKHOUSE_URL: http://clickhouse:8123
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-langfuse}
      REDIS_CONNECTION_STRING: redis://langfuse-redis:6379
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      SALT: ${SALT}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      HOSTNAME: 0.0.0.0
      LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: ${MINIO_MEDIA_BUCKET:-langfuse-media}
      LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: http://minio:9091
      LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: "true"
      LANGFUSE_S3_MEDIA_UPLOAD_REGION: ${LANGFUSE_S3_MEDIA_UPLOAD_REGION}
      LANGFUSE_S3_EVENT_UPLOAD_BUCKET: ${MINIO_EVENT_BUCKET:-langfuse-events}
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: http://minio:9091
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: "true"
      LANGFUSE_S3_EVENT_UPLOAD_REGION: ${LANGFUSE_S3_EVENT_UPLOAD_REGION}
      LANGFUSE_DEBUG: "true"
      LOG_LEVEL: "debug"
    restart: unless-stopped
    networks:
      - axstudio_net

  langfuse-worker:
    build:
      context: ../langfuse
      dockerfile: ${LANGFUSE_WORKER_DOCKERFILE_PATH:-worker/Dockerfile}
    image: ax/langfuse-worker:local
    container_name: langfuse-worker
    depends_on:
      - langfuse-web
    environment:
      DATABASE_URL: postgresql://${LFS_PG_USER}:${LFS_PG_PASSWORD}@lfs-postgres:5432/${LFS_PG_DB}
      CLICKHOUSE_MIGRATION_URL: clickhouse://clickhouse:9990
      CLICKHOUSE_URL: http://clickhouse:8123
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-langfuse}
      REDIS_CONNECTION_STRING: redis://langfuse-redis:6379
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      SALT: ${SALT}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      HOSTNAME: 0.0.0.0
      PORT: 3030
      LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: ${MINIO_MEDIA_BUCKET:-langfuse-media}
      LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: http://minio:9091
      LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: "true"
      LANGFUSE_S3_MEDIA_UPLOAD_REGION: ${LANGFUSE_S3_MEDIA_UPLOAD_REGION}
      LANGFUSE_S3_EVENT_UPLOAD_BUCKET: ${MINIO_EVENT_BUCKET:-langfuse-events}
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: http://minio:9091
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: "true"
      LANGFUSE_S3_EVENT_UPLOAD_REGION: ${LANGFUSE_S3_EVENT_UPLOAD_REGION}
      LANGFUSE_DEBUG: "true"
      LOG_LEVEL: "debug"
    restart: unless-stopped
    networks:
      - axstudio_net

  # ---------------------------
  # Arize Phoenix (이미지 그대로 사용)
  # ---------------------------
  phoenix:
    image: ${PHOENIX_IMAGE:-arizephoenix/phoenix:latest}
    container_name: phoenix
    environment:
      PHOENIX_PORT: ${PHOENIX_PORT:-6006}
      PHOENIX_GRPC_PORT: ${PHOENIX_GRPC_PORT:-4317}
      PHOENIX_ALLOW_EXTERNAL_RESOURCES: ${PHOENIX_ALLOW_EXTERNAL_RESOURCES:-false}
      # 🔽 인증 활성화
      PHOENIX_ENABLE_AUTH: ${PHOENIX_ENABLE_AUTH:-true}
      PHOENIX_SECRET: ${PHOENIX_SECRET}
      PHOENIX_ADMIN_EMAIL: ${PHOENIX_ADMIN_EMAIL}
      PHOENIX_ADMIN_PASSWORD: ${PHOENIX_ADMIN_PASSWORD}
      # (선택) Programmatic API Key 발급 API 사용하려면 필요
      PHOENIX_ADMIN_SECRET: ${PHOENIX_ADMIN_SECRET}
    ports:
      - "${PHOENIX_PORT:-6006}:6006"
      - "${PHOENIX_GRPC_PORT:-4317}:4317"
    restart: unless-stopped
    networks:
      - axstudio_net

  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    ports: []
    restart: unless-stopped
    networks:
      - axstudio_net